package MonkeyTest;

import java.util.HashSet;
import java.util.Random;

import org.junit.*;

import Application.ChapsChallenge;
import Maze.Board;
import Maze.Game;
import Maze.Position;
import Maze.BoardObjects.Actors.Player;



/**
 * @author Ben
 *	Class to group together all tests to run 
 */
public class TestSuite {
	private Game tester;
	// private ChapsChallenge t; for visual testing
	
	/**
	 * @param board - board object should have been generated by MonkeyTest
	 * 
	 */
	public TestSuite(Board board) {
		// t = new ChapsChallenge();
		// tester = t.getGame();
		
		tester =  new Game(board, new Player(new Position(4, 4)), new HashSet<>()); //PLACEHOLDER, need to implement level loader
		
	}
	
	/**
	 * A method to generate non-intelligent random input, each movement has an equal chance of being called each iteration
	 */
	@Test public void randomMovement() {				
		Random ran = new Random();
		float num = ran.nextFloat();
		
		if(num < 0.25) { tester.movePlayer(Game.DIRECTION.UP);}
		else if(num < 0.5) {tester.movePlayer(Game.DIRECTION.DOWN);}
		else if(num < 0.75) {tester.movePlayer(Game.DIRECTION.LEFT);}
		else { tester.movePlayer(Game.DIRECTION.RIGHT);}
	}
	
	/**
	 * A method to generate intelligent input, will move the player towards a predefined goal
	 */
	@Test public void intelligentMovement() { 
		
	}
	
	
	

	
}
