package nz.ac.vuw.ecs.swen225.gp20.MonkeyTest;

import java.util.Random;
import org.junit.*;
import Maze.Board;
import Maze.Game;
import Persistence.Level;



/**
 * @author Ben
 *	Class for methods for use in tests
 */
public class TestSuite {
	private Game tester;

	/**
	 * @param board - board object should have been generated by MonkeyTest
	 * @param level - info for level
	 * 
	 */
	public TestSuite(Board board, Level level) {
		

		tester =  new Game(board, level.getPlayer(), level.getEnemies()); 

	}

	/**
	 * A method to generate non-intelligent random input, each movement has an equal chance of being called each iteration
	 */
 public void randomMovement() {				
		Random ran = new Random();
		float num = ran.nextFloat();

		if(num < 0.25) { tester.movePlayer(Game.DIRECTION.UP);}
		else if(num < 0.5) {tester.movePlayer(Game.DIRECTION.DOWN);}
		else if(num < 0.75) {tester.movePlayer(Game.DIRECTION.LEFT);}
		else { tester.movePlayer(Game.DIRECTION.RIGHT);}
	}

	/**
	 * A method to generate intelligent input, will move the player towards a predefined goal
	 */





}
